"""Remove foreign key from etc_usage

Revision ID: 21c21e289b81
Revises: 516fa1af0f40
Create Date: 2025-04-04 09:28:28.694036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21c21e289b81'
down_revision = '516fa1af0f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etc_usage', schema=None) as batch_op:
        batch_op.alter_column('vehicle_number',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etc_usage', schema=None) as batch_op:
        batch_op.alter_column('vehicle_number',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
