"""Initial migration with Hluggage tables

Revision ID: 516fa1af0f40
Revises: 
Create Date: 2025-04-04 09:20:24.372168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516fa1af0f40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('etc_usage', schema=None) as batch_op:
     #   batch_op.create_foreign_key(None, 'vehicles', ['vehicle_number'], ['vehicle_number'])

    # ### end Alembic commands ###


def downgrade():
    passs# ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('etc_usage', schema=None) as batch_op:
     #   batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
